version: '3.8'

services:
  stock-analyzer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - NEWS_API_KEY=8cff18d9c3c14e17ab12d23dda19e155
      - ALPHA_VANTAGE_API_KEY=3YAEF3HDT330174E
      - DEFAULT_LANGUAGE=en
      - DEFAULT_NUM_ARTICLES=5
      - PORT=5000
    volumes:
      - .:/app
    restart: unless-stopped
