services:
  - type: web
    name: stock-market-analyzer
    env: python
    runtime: python-3.11.7
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    envVars:
      - key: NEWS_API_KEY
        sync: false
      - key: ALPHA_VANTAGE_API_KEY
        sync: false
      - key: DEFAULT_LANGUAGE
        value: en
      - key: DEFAULT_NUM_ARTICLES
        value: 5
      - key: FLASK_ENV
        value: production
