services:
  - type: web
    name: stock-market-analyzer
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NEWS_API_KEY
        sync: false
      - key: ALPHA_VANTAGE_API_KEY  
        sync: false
      - key: DEFAULT_LANGUAGE
        value: en
      - key: DEFAULT_NUM_ARTICLES
        value: 5
      - key: FLASK_ENV
        value: production
